import { NextRequest, NextResponse } from "next/server";

const DEMO_JOBS = [
  { id: "demo-1",  jobNumber: "JOB-260601-1021", status: "COLLECTED",      deviceBrand: "Apple",   deviceModel: "iPhone 15 Pro",  deviceColor: "Natural Titanium", imei: "354678901234567", repairType: "Screen Replacement",  faultDescription: "Cracked screen replacement",           quotedPrice: 249, finalPrice: 249, technicianNotes: "OEM screen fitted. Touch and Face ID working correctly.", internalNotes: null, followUpSent: true,  collectedAt: new Date(Date.now() - 10 * 86400000).toISOString(), estimatedReady: null, createdAt: new Date(Date.now() - 13 * 86400000).toISOString(), customer: { name: "James Whitfield",  phone: "07700 900123", email: "james.whitfield@email.com" }, statusHistory: [{ id: "h1a", status: "RECEIVED", smsSent: true, createdAt: new Date(Date.now() - 13 * 86400000).toISOString() }, { id: "h1b", status: "DIAGNOSED", smsSent: true, createdAt: new Date(Date.now() - 12 * 86400000).toISOString() }, { id: "h1c", status: "IN_REPAIR", smsSent: true, createdAt: new Date(Date.now() - 11 * 86400000).toISOString() }, { id: "h1d", status: "READY", smsSent: true, createdAt: new Date(Date.now() - 10 * 86400000).toISOString() }, { id: "h1e", status: "COLLECTED", smsSent: false, createdAt: new Date(Date.now() - 10 * 86400000).toISOString() }] },
  { id: "demo-2",  jobNumber: "JOB-260602-1047", status: "COLLECTED",      deviceBrand: "Samsung", deviceModel: "Galaxy S24",     deviceColor: "Phantom Black",    imei: "358291047382910", repairType: "Battery Replacement", faultDescription: "Battery swollen, not charging",        quotedPrice: 129, finalPrice: 129, technicianNotes: "Genuine Samsung battery installed. Charge cycle reset.", internalNotes: null, followUpSent: true,  collectedAt: new Date(Date.now() - 9  * 86400000).toISOString(), estimatedReady: null, createdAt: new Date(Date.now() - 12 * 86400000).toISOString(), customer: { name: "Priya Sharma",     phone: "07700 900456", email: "priya.sharma@gmail.com" },    statusHistory: [{ id: "h2a", status: "RECEIVED", smsSent: true, createdAt: new Date(Date.now() - 12 * 86400000).toISOString() }, { id: "h2b", status: "DIAGNOSED", smsSent: true, createdAt: new Date(Date.now() - 11 * 86400000).toISOString() }, { id: "h2c", status: "IN_REPAIR", smsSent: true, createdAt: new Date(Date.now() - 10 * 86400000).toISOString() }, { id: "h2d", status: "READY", smsSent: true, createdAt: new Date(Date.now() - 9  * 86400000).toISOString() }, { id: "h2e", status: "COLLECTED", smsSent: false, createdAt: new Date(Date.now() - 9  * 86400000).toISOString() }] },
  { id: "demo-3",  jobNumber: "JOB-260603-1058", status: "COLLECTED",      deviceBrand: "Apple",   deviceModel: "iPhone 14",      deviceColor: "Blue",             imei: "356781234509876", repairType: "Water Damage",        faultDescription: "Water damage — full diagnostic",       quotedPrice: 180, finalPrice: 180, technicianNotes: "Full board clean. Charging port replaced. All functions restored.", internalNotes: "Customer warned about residual risk.", followUpSent: true, collectedAt: new Date(Date.now() - 8 * 86400000).toISOString(), estimatedReady: null, createdAt: new Date(Date.now() - 11 * 86400000).toISOString(), customer: { name: "Daniel O'Brien",   phone: "07700 900789", email: null },                         statusHistory: [{ id: "h3a", status: "RECEIVED", smsSent: true, createdAt: new Date(Date.now() - 11 * 86400000).toISOString() }, { id: "h3b", status: "DIAGNOSED", smsSent: true, createdAt: new Date(Date.now() - 10 * 86400000).toISOString() }, { id: "h3c", status: "AWAITING_PARTS", smsSent: true, createdAt: new Date(Date.now() - 9 * 86400000).toISOString() }, { id: "h3d", status: "IN_REPAIR", smsSent: true, createdAt: new Date(Date.now() - 8 * 86400000).toISOString() }, { id: "h3e", status: "READY", smsSent: true, createdAt: new Date(Date.now() - 8 * 86400000).toISOString() }, { id: "h3f", status: "COLLECTED", smsSent: false, createdAt: new Date(Date.now() - 8 * 86400000).toISOString() }] },
  { id: "demo-4",  jobNumber: "JOB-260604-1073", status: "COLLECTED",      deviceBrand: "Google",  deviceModel: "Pixel 8",        deviceColor: "Obsidian",         imei: null,              repairType: "Back Glass Repair",   faultDescription: "Back glass cracked",                   quotedPrice: 95,  finalPrice: 95,  technicianNotes: "Back glass replaced with OEM part.", internalNotes: null, followUpSent: false, collectedAt: new Date(Date.now() - 7 * 86400000).toISOString(), estimatedReady: null, createdAt: new Date(Date.now() - 10 * 86400000).toISOString(), customer: { name: "Sophie Nguyen",    phone: "07700 900321", email: "sophie.n@outlook.com" },      statusHistory: [{ id: "h4a", status: "RECEIVED", smsSent: true, createdAt: new Date(Date.now() - 10 * 86400000).toISOString() }, { id: "h4b", status: "IN_REPAIR", smsSent: true, createdAt: new Date(Date.now() - 9 * 86400000).toISOString() }, { id: "h4c", status: "READY", smsSent: true, createdAt: new Date(Date.now() - 7 * 86400000).toISOString() }, { id: "h4d", status: "COLLECTED", smsSent: false, createdAt: new Date(Date.now() - 7 * 86400000).toISOString() }] },
  { id: "demo-5",  jobNumber: "JOB-260605-1089", status: "COLLECTED",      deviceBrand: "OnePlus", deviceModel: "12",             deviceColor: "Silky Black",      imei: null,              repairType: "Port Repair",         faultDescription: "Charging port replaced",               quotedPrice: 75,  finalPrice: 75,  technicianNotes: "USB-C port replaced. Charging confirmed at full speed.", internalNotes: null, followUpSent: false, collectedAt: new Date(Date.now() - 6 * 86400000).toISOString(), estimatedReady: null, createdAt: new Date(Date.now() - 9 * 86400000).toISOString(), customer: { name: "Marcus Webb",      phone: "07700 900654", email: null },                         statusHistory: [{ id: "h5a", status: "RECEIVED", smsSent: true, createdAt: new Date(Date.now() - 9 * 86400000).toISOString() }, { id: "h5b", status: "DIAGNOSED", smsSent: true, createdAt: new Date(Date.now() - 8 * 86400000).toISOString() }, { id: "h5c", status: "IN_REPAIR", smsSent: true, createdAt: new Date(Date.now() - 7 * 86400000).toISOString() }, { id: "h5d", status: "READY", smsSent: true, createdAt: new Date(Date.now() - 6 * 86400000).toISOString() }, { id: "h5e", status: "COLLECTED", smsSent: false, createdAt: new Date(Date.now() - 6 * 86400000).toISOString() }] },
  { id: "demo-6",  jobNumber: "JOB-260607-1102", status: "IN_REPAIR",      deviceBrand: "Apple",   deviceModel: "iPhone 15 Pro",  deviceColor: "White Titanium",   imei: "354123098765432", repairType: "Face ID Repair",      faultDescription: "Face ID not working after drop",       quotedPrice: 199, finalPrice: null, technicianNotes: "Flex cable ordered. Awaiting fitment.", internalNotes: "Handle with care — customer is a repeat.", followUpSent: false, collectedAt: null, estimatedReady: new Date(Date.now() + 1 * 86400000).toISOString(), createdAt: new Date(Date.now() - 7 * 86400000).toISOString(), customer: { name: "Aisha Patel",      phone: "07700 900987", email: "aisha.patel@work.co.uk" },    statusHistory: [{ id: "h6a", status: "RECEIVED", smsSent: true, createdAt: new Date(Date.now() - 7 * 86400000).toISOString() }, { id: "h6b", status: "DIAGNOSED", smsSent: true, createdAt: new Date(Date.now() - 6 * 86400000).toISOString() }, { id: "h6c", status: "AWAITING_PARTS", smsSent: true, createdAt: new Date(Date.now() - 5 * 86400000).toISOString() }, { id: "h6d", status: "IN_REPAIR", smsSent: true, createdAt: new Date(Date.now() - 1 * 86400000).toISOString() }] },
  { id: "demo-7",  jobNumber: "JOB-260608-1115", status: "AWAITING_PARTS", deviceBrand: "Samsung", deviceModel: "Galaxy S24",     deviceColor: "Cobalt Violet",    imei: null,              repairType: "Camera Repair",       faultDescription: "Camera lens shattered",                quotedPrice: 145, finalPrice: null, technicianNotes: "Camera module ordered from supplier. ETA 2 days.", internalNotes: null, followUpSent: false, collectedAt: null, estimatedReady: new Date(Date.now() + 2 * 86400000).toISOString(), createdAt: new Date(Date.now() - 6 * 86400000).toISOString(), customer: { name: "Tom Gallagher",    phone: "07700 900147", email: "tom.g@hotmail.com" },           statusHistory: [{ id: "h7a", status: "RECEIVED", smsSent: true, createdAt: new Date(Date.now() - 6 * 86400000).toISOString() }, { id: "h7b", status: "DIAGNOSED", smsSent: true, createdAt: new Date(Date.now() - 5 * 86400000).toISOString() }, { id: "h7c", status: "AWAITING_PARTS", smsSent: true, createdAt: new Date(Date.now() - 4 * 86400000).toISOString() }] },
  { id: "demo-8",  jobNumber: "JOB-260609-1128", status: "DIAGNOSED",      deviceBrand: "Apple",   deviceModel: "iPhone 14",      deviceColor: "Midnight",         imei: "356987654321098", repairType: "Software / Network",  faultDescription: "No service after iOS update",          quotedPrice: 60,  finalPrice: null, technicianNotes: "Network stack issue identified. Reset required.", internalNotes: null, followUpSent: false, collectedAt: null, estimatedReady: new Date(Date.now() + 1 * 86400000).toISOString(), createdAt: new Date(Date.now() - 5 * 86400000).toISOString(), customer: { name: "Chloe Martinez",   phone: "07700 900258", email: null },                         statusHistory: [{ id: "h8a", status: "RECEIVED", smsSent: true, createdAt: new Date(Date.now() - 5 * 86400000).toISOString() }, { id: "h8b", status: "DIAGNOSED", smsSent: true, createdAt: new Date(Date.now() - 4 * 86400000).toISOString() }] },
  { id: "demo-9",  jobNumber: "JOB-260610-1141", status: "READY",          deviceBrand: "Google",  deviceModel: "Pixel 8",        deviceColor: "Hazel",            imei: null,              repairType: "Screen Replacement",  faultDescription: "Screen unresponsive at bottom",        quotedPrice: 110, finalPrice: 110, technicianNotes: "Digitiser replaced. Full touch response confirmed.", internalNotes: null, followUpSent: true, collectedAt: null, estimatedReady: null, createdAt: new Date(Date.now() - 3 * 86400000).toISOString(), customer: { name: "Ryan Fletcher",    phone: "07700 900369", email: "ryan.fletcher@gmail.com" },   statusHistory: [{ id: "h9a", status: "RECEIVED", smsSent: true, createdAt: new Date(Date.now() - 3 * 86400000).toISOString() }, { id: "h9b", status: "DIAGNOSED", smsSent: true, createdAt: new Date(Date.now() - 2 * 86400000).toISOString() }, { id: "h9c", status: "IN_REPAIR", smsSent: true, createdAt: new Date(Date.now() - 1 * 86400000).toISOString() }, { id: "h9d", status: "READY", smsSent: true, createdAt: new Date(Date.now() - 0.5 * 86400000).toISOString() }] },
  { id: "demo-10", jobNumber: "JOB-260611-1154", status: "READY",          deviceBrand: "OnePlus", deviceModel: "12",             deviceColor: "Flowy Emerald",    imei: null,              repairType: "Speaker Repair",      faultDescription: "Speaker crackling on calls",           quotedPrice: 55,  finalPrice: 55,  technicianNotes: "Earpiece speaker replaced.", internalNotes: null, followUpSent: true, collectedAt: null, estimatedReady: null, createdAt: new Date(Date.now() - 2 * 86400000).toISOString(), customer: { name: "Fatima Al-Rashid", phone: "07700 900471", email: "fatima.ar@icloud.com" },       statusHistory: [{ id: "h10a", status: "RECEIVED", smsSent: true, createdAt: new Date(Date.now() - 2 * 86400000).toISOString() }, { id: "h10b", status: "IN_REPAIR", smsSent: true, createdAt: new Date(Date.now() - 1 * 86400000).toISOString() }, { id: "h10c", status: "READY", smsSent: true, createdAt: new Date(Date.now() - 0.3 * 86400000).toISOString() }] },
  { id: "demo-11", jobNumber: "JOB-260612-1167", status: "READY",          deviceBrand: "Apple",   deviceModel: "iPhone 15 Pro",  deviceColor: "Black Titanium",   imei: "354765432109876", repairType: "Microphone Repair",   faultDescription: "Microphone not working during calls",  quotedPrice: 89,  finalPrice: 89,  technicianNotes: "Microphone flex replaced. Call audio confirmed.", internalNotes: null, followUpSent: false, collectedAt: null, estimatedReady: null, createdAt: new Date(Date.now() - 1 * 86400000).toISOString(), customer: { name: "Ben Holloway",     phone: "07700 900582", email: "ben.holloway@email.com" },    statusHistory: [{ id: "h11a", status: "RECEIVED", smsSent: true, createdAt: new Date(Date.now() - 1 * 86400000).toISOString() }, { id: "h11b", status: "DIAGNOSED", smsSent: true, createdAt: new Date(Date.now() - 0.8 * 86400000).toISOString() }, { id: "h11c", status: "IN_REPAIR", smsSent: true, createdAt: new Date(Date.now() - 0.5 * 86400000).toISOString() }, { id: "h11d", status: "READY", smsSent: true, createdAt: new Date(Date.now() - 0.2 * 86400000).toISOString() }] },
  { id: "demo-12", jobNumber: "JOB-260612-1178", status: "IN_REPAIR",      deviceBrand: "Samsung", deviceModel: "Galaxy S24",     deviceColor: "Marble Gray",      imei: null,              repairType: "Screen Replacement",  faultDescription: "OLED screen replacement",              quotedPrice: 220, finalPrice: null, technicianNotes: "OLED panel fitted. Colour calibration in progress.", internalNotes: null, followUpSent: false, collectedAt: null, estimatedReady: new Date(Date.now() + 1 * 86400000).toISOString(), createdAt: new Date(Date.now() - 1 * 86400000).toISOString(), customer: { name: "Laura Brennan",    phone: "07700 900693", email: "laura.b@outlook.com" },        statusHistory: [{ id: "h12a", status: "RECEIVED", smsSent: true, createdAt: new Date(Date.now() - 1 * 86400000).toISOString() }, { id: "h12b", status: "DIAGNOSED", smsSent: true, createdAt: new Date(Date.now() - 0.7 * 86400000).toISOString() }, { id: "h12c", status: "IN_REPAIR", smsSent: true, createdAt: new Date(Date.now() - 0.3 * 86400000).toISOString() }] },
  { id: "demo-13", jobNumber: "JOB-260613-1189", status: "RECEIVED",       deviceBrand: "Apple",   deviceModel: "iPhone 14",      deviceColor: "Purple",           imei: null,              repairType: "Button Repair",       faultDescription: "Home button stuck / not clicking",     quotedPrice: null, finalPrice: null, technicianNotes: null, internalNotes: null, followUpSent: false, collectedAt: null, estimatedReady: null, createdAt: new Date().toISOString(), customer: { name: "Noah Chambers",    phone: "07700 900704", email: null },                         statusHistory: [{ id: "h13a", status: "RECEIVED", smsSent: true, createdAt: new Date().toISOString() }] },
  { id: "demo-14", jobNumber: "JOB-260613-1190", status: "RECEIVED",       deviceBrand: "Google",  deviceModel: "Pixel 8",        deviceColor: "Snow",             imei: null,              repairType: "Water Damage",        faultDescription: "Phone won't turn on after getting wet", quotedPrice: null, finalPrice: null, technicianNotes: null, internalNotes: null, followUpSent: false, collectedAt: null, estimatedReady: null, createdAt: new Date().toISOString(), customer: { name: "Imogen Clarke",    phone: "07700 900815", email: "imogen.c@gmail.com" },        statusHistory: [{ id: "h14a", status: "RECEIVED", smsSent: true, createdAt: new Date().toISOString() }] },
];

export async function GET(_req: NextRequest, { params }: { params: { id: string } }) {
  try {
    const { prisma } = await import("@/lib/prisma");
    const job = await prisma.repairJob.findUnique({
      where: { id: params.id },
      include: { customer: true, statusHistory: { orderBy: { createdAt: "asc" } } },
    });
    if (job) return NextResponse.json(job);
  } catch {
    // DB unavailable — fall through to demo data
  }

  const demo = DEMO_JOBS.find(j => j.id === params.id);
  if (!demo) return NextResponse.json({ error: "Not found" }, { status: 404 });
  return NextResponse.json(demo);
}

export async function PATCH(req: NextRequest, { params }: { params: { id: string } }) {
  try {
    const { prisma } = await import("@/lib/prisma");
    const body = await req.json();
    const job = await prisma.repairJob.update({
      where: { id: params.id },
      data: {
        quotedPrice: body.quotedPrice !== undefined ? parseFloat(body.quotedPrice) || null : undefined,
        finalPrice: body.finalPrice !== undefined ? parseFloat(body.finalPrice) || null : undefined,
        technicianNotes: body.technicianNotes,
        internalNotes: body.internalNotes,
        estimatedReady: body.estimatedReady ? new Date(body.estimatedReady) : undefined,
      },
      include: { customer: true },
    });
    return NextResponse.json(job);
  } catch {
    // Demo mode — return the demo job unchanged
    const demo = DEMO_JOBS.find(j => j.id === params.id);
    if (!demo) return NextResponse.json({ error: "Not found" }, { status: 404 });
    return NextResponse.json(demo);
  }
}
